services:
  # 前端服务
  homepagev2:
    build: .
    image: homepagev2:latest
    container_name: homepagev2
    networks:
      - proxy-tier
    restart: unless-stopped
networks:
  proxy-tier:
    external: true

